### ISSUE TITLE
Move API docs to Slate API Docs Framework.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#242]
We have API docs, but they're boring and aren't fun:

![image](https://user-images.githubusercontent.com/9611008/169073982-114d2042-f702-4dcb-961a-ce67688c4e9b.png)

Let's move them to Slate so that they're not boring and much more useable:

![image](https://user-images.githubusercontent.com/9611008/169074100-7348e04c-7cde-4755-86b9-4c44bd50049b.png)

## Tasks

- [ ] Spin up Slate API page.
- [ ] Grab API docs from lotus repo.
- [ ] Port into API page.
- [ ] Style API page to match Lotus docs.

**Comment by BlocksOnAChain** [comment]
@jennijuju hey. Would be great if you have some inputs or if someone from the TSE side wants to be involved in our "rebranding" of API docs, since it will relate to Lotus API docs, at some point. Just wanted to raise visibility to your side of things.
