### ISSUE TITLE
New Lotus docs

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#4]
Lotus Docs is becoming it's own website and repo again! This issue the main holder issue for all the tasks that we need to complete.

## Tasks

- [x] Create a new repository for Lotus documentation. Edit: [already exists](https://github.com/filecoin-project/lotus-docs)
- [x] Create a site for Lotus docs to use.
- [x] Go through each section in Filecoin docs and list which pages/sections need to be lifted out:
    - [x] About Filecoin
    - [x] Networks
    - [x] Get Started
    - [x] Store
    - [x] Mine
    - [x] Build
    - [x] Reference
- [x] #3 
- [x] #15
- [ ] #5
- [x] #6
- [ ] #7
- [x] #8
- [x] #9
- [x] #10

Further tasks will be added as this project progresses.

Here's some extra tasks that don't have to be completed for this issue to be closed, but are nice to have:

- [ ] #13
- [ ] #14
- [x] #11
- [x] #12

**Comment by BigLep** [comment]
@johnnymatthews : are we going to remove or redirect the Lotus docs under docs.filecoin.io (e.g., https://docs.filecoin.io/get-started/lotus/ )?

**Comment by johnnymatthews** [comment]
@BigLep we are. In fact, that's what this PR is for: https://github.com/filecoin-project/filecoin-docs/pull/1109

**Comment by johnnymatthews** [comment]
Project has been merged! lotus.filecoin.io
