### ISSUE TITLE
Reflect that the Legacy Lotus-Miner Markets sub-system is EOL

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#492]
> The Legacy Lotus/Lotus-Miner Markets sub-system [reached EOL](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0) at the end of the 31st January 2023, and the Markets sub-subsytem in Lotus-Miner will be set to disabled by default after the Network 18 upgrade.

**User Story:**

- As a Storage Provider (SP) or Developer, I need the Lotus documentation to be updated to reflect that the Legacy Lotus-Miner Markets sub-system is End-Of-Life (EOL) and being deprecated, so that I have a clear understanding of the transition path to Boost and can easily comprehend the active components of the Lotus-Miner codebase.

**Acceptance criteria:**

- The documentation should adhere to old links, but should have warnings that these docs are outdated and point to the Boost documentation.
- Lotus documentation should clearly indicate that the Legacy Lotus-Miner Markets sub-system is EOL and that users should migrate to Boost.
- The Tutorials section should be updated with new content reflecting newer methods for storing and retrieving data in the Filecoin network

**Techincal Scope:**

```
├─ Operate/
│  ├─ Index Provider
│  ├─ Dynamic Retrival Pricing
│  ├─ Dagstore
│  ├─ Manage storage deals
├─ Advanced configurations/
│  ├─ Split Markets
│  ├─ Market
```

```[tasklist]
### Tasks
- [x] Move `Dynamic retrival pricing` to kb: #493 
- [x] Move `Index provider` to kb: #495 
- [x] Move `Dagstore` to kb: #497 
- [x] Move `Connectivity` to kb: #578 
- [x] Move `Split Markets` to kb: #498 
- [ ] https://github.com/filecoin-project/lotus-docs/issues/601
- [ ] https://github.com/filecoin-project/lotus-docs/issues/602
- [ ] https://github.com/filecoin-project/lotus-docs/issues/603
```

For the Tutorials part of the Lotus docs these pages would need to fixed to reflect the newer methods to store and retrieve:

```
├─ Lotus/
│  ├─ Set up
│  ├─ Store data
│  ├─ Retrieve data
│  ├─ Large files
│  ├─ Payment channels
```

```[tasklist]
### Tutorials tasks
- [ ] Find alternative content to the `Set up` and `Store data` reflecting newer methods for storing data in the Filecoin network
- [x] #507
- [x] #509
- [ ] https://github.com/filecoin-project/lotus-docs/issues/501
- [x] Review `Large files` page
- [x] Review `Payment Channels` page
```

**Comment by smagdali** [comment]
Also the retrieval sections of the lotus tutorial, need to be updated to use boost? I can create a separate issue if you'd prefer. https://lotus.filecoin.io/tutorials/lotus/store-and-retrieve/retrieve-data/

**Comment by rjan90** [comment]
> Also the retrieval sections of the lotus tutorial, need to be updated to use boost?

Yes, that would be great! We should start redirecting our users to https://boost.filecoin.io/getting-started/boost-client. The depreciation on the client side will take a bit longer then on the storage provider side, so the markets code functionality will be around a bit longer, but best to guide our users to the relevant tools.

Current depreciation plan looks like this: https://github.com/filecoin-project/lotus/issues/10267

**Comment by rjan90** [comment]
For the Tutorials part of the Lotus docs these pages would need to fixed to reflect the newer methods to store and retrieve:

```
├─ Lotus/
│  ├─ Set up
│  ├─ Store data
│  ├─ Retrieve data
│  ├─ Payment channels
```

- [ ] Set up
- [ ] Store data
- [ ] Retrieve data
- [ ] Payment
