### ISSUE TITLE
Move `Manage storage deals` to kb:

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#601]
**User Story:**

- As a Storage Provider (SP) or Developer, I need the Lotus documentation to be updated to reflect that the Legacy Lotus-Miner Markets sub-system is End-Of-Life (EOL) and being deprecated, so that I have a clear understanding of the transition path to Boost/other markets systems and can easily comprehend the active components of the Lotus-Miner codebase.

**Acceptance criteria:**

- The documentation should adhere to old links, but should have warnings that these docs are outdated and point to the Boost documentation.
- Lotus documentation should clearly indicate that the Legacy Lotus-Miner Markets sub-system is EOL and that users should migrate to Boost.

```[tasklist]
### Tasks
- [x] Move the Manage storage deals page to the knowledge-base
- [x] Keep links intact
- [x] Add warnings that the page is outdated
```
