### ISSUE TITLE
Create a proposed map for a new Lotus docs re-org.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus-docs#65]
Similar to how a map was generated for the, at the time, [new IPFS docs structure](https://github.com/ipfs/ipfs-docs/issues/265), let's create a high-level map for the content that's going to fit into Lotus docs.

# Tasks

- [ ] Create a high-level map with each section and sub-section mapped out.
- [ ] Add individual pages to each section.
- [ ] Pass to the Lotus team for review to make sure we're not missing anything.

**Comment by johnnymatthews** [comment]
Map draft here: https://miro.com/app/board/uXjVOWo-d_E=/?invite_link_id=144489624909

**Comment by johnnymatthews** [comment]
[Map here.](https://github.com/filecoin-project/lotus-docs/files/7974221/Re-org.mindmap.1.pdf)
