### ISSUE TITLE
Lotus SplitStore documentation

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/lotus-docs#71]
**What's the subject of the item you're requesting?**
SplitStore: An actively scalable blockstore for the Filecoin chain

**What's the content of the item you're requesting?**
_Note_: This will be experimental in 1.11.1, so we want to denote this at the top of the content.
This is an extension and replacement of the SplitStore readme in the Lotus repo, https://github.com/filecoin-project/lotus/blob/v1.11.1-rc2/blockstore/splitstore/README.md. We're looking to create 3 sections/pages for the SplitStore:
- Concept docs that describe what the SplitStore is and the value it has.
- Operator docs instructing users how to enable/disable it and how to perform rollbacks as needed. Much of this is in the current [readme](https://github.com/filecoin-project/lotus/blob/v1.11.1-rc2/blockstore/splitstore/README.md) but could use clarification.
- Troubleshooting/FAQs

**What will the user know how to do after going through this item?**
Why the SplitStore is useful, if they should use it, and how to configure it.

**Would you be interested in helping create this item?**
Yes, we'll be creating PRs for this over this week and next. Reviews from the docs team will be very helpful here.

**Comment by johnnymatthews** [comment]
Since most of the docs already exist, all this issue needs is one of the docs team to go through and _editorize_ things.

## Tasks

- [ ] Review [Split-store readme](https://github.com/filecoin-project/lotus/blob/master/blockstore/splitstore/README.md).
- [ ] Create new page for Split-store under **Storage providers**.
- [ ] Add links to internal pages from within this new page.

**Comment by rjan90** [comment]
Documenting the SplitStoreV2 is being added with this PR: https://github.com/filecoin-project/lotus-docs/pull/332

**Comment by rjan90** [comment]
Closing this issue ticket now since we have a section for the `SplitStoreV2` in the documentation now 🎉! https://lotus.filecoin.io/lotus/manage/chain-management/#splitstore.

Thanks for the ticket!
