### ISSUE TITLE
Move off of Protocol Labs Inc Fleek account

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/lotus-docs#742]
## Done Criteria
lotus.filecoin.io is no longer publishing using Protocol Labs Inc's Fleek account.  This could mean:
1. Use a FilOz-owned account
2. Remove Fleek pulblishing (😞 from a "supporting the dweb" movement regard)

## Why Important
Protocol Labs Inc isn't staffed to manage the sites of disparate teams and this runs counter to teams "owning their stuff". 

## Notes
SEAD sent a [form requesting our plan.](https://forms.gle/ZiqZkUEz8Yg6CU23A)  I filled it in saying we would have migration out of Protocol Labs Inc Fleek by 2024-07-31.

```[tasklist]
## Tasks
- [x] @rjan90 Store infra@filoz.org fleek.xyz credentials in FilOz 1password
- [x] @rjan90 Store infra@filoz.org fleek9625.zendesk.com credentials in FilOz 1password
- [x] Give Biglep admin access to lotus-docs repo: https://github.com/filecoin-project/github-mgmt/pull/59
- [x] Get site publishing into fleek.xyz subdomain
- [x] Get lotus.filecoin.io configured with fleek.xyz
- [x] Document public publishing: https://github.com/filecoin-project/lotus-docs/pull/756
- [x] Shut down / remove lotus-docs in fleek.co by removing GitHub app integration of "fleek.co"
- [x] Understand and either document or remove other GitHub App integrations
```

**Comment by BigLep** [comment]
I haven't done this yet.  I put this down to do in August 2024.

**Comment by rjan90** [comment]
What is the current status on this? We got an update that Protocol Labs’ Tina Cloud and Fleek accounts will be shut-down by the EOM, so we need to move the lotus.filecoin.io website off of Fleek by then. 

Both I and @TippyFlitsUK can help with the migration, to take some things off your plate @BigLep.

**Comment by BigLep** [comment]
Thanks for checking.  
I haven't done anything on this yet.  When I volunteered for it, I was assuming there would be more open bandwidth to tackle these kind of things.  I don't have experience with Fleek or how Lotus Docs is configured, but I'm game to go figure it out.  Unless @rjan90 or @TippyFlitsUK want to tackle it because they think it would be easy because they have done it before and have access to team credit cards, 1password accounts, etc. then I will plan on starting 2024-08-15 to get it done in time.

**Comment by smagdali** [comment]
@BigLep I'm curious- are you planning to migrate it to fleek.xyz, or start hosting elsewhere?

**Comment by BigLep** [comment]
@rjan90 : I don't have write-access to FilOz's infra 1password vault.  Can you please add an entry for fleek.xyz

Login email: infa@fleek.xyz
Username: filoz
There isn't a password since uses email verification for login.

Thanks

**Comment by BigLep** [comment]
> I'm curious- are you planning to migrate it to fleek.xyz, or start hosting elsewhere?

@smagdali : I was planning to stay on Fleek.  Do you have other suggestions/recommendations?

**Comment by BigLep** [comment]
2024-08-15 status: 
* I created a infra@filoz.org Fleek account
* I am trying to get admin access to the lotus-docs repo: https://github.com/filecoin-project/github-mgmt/pull/59
* I have made reachout to SEAD to collaborate on this by DMing "[@Daniel Bisgrove (SEAD)](https://filecoinproject.slack.com/team/U07517VLVL5)" on FIL Slack.

**Comment by BigLep** [comment]
From [@Daniel Bisgrove (SEAD)](https://filecoinproject.slack.com/team/U07517VLVL5)

> I can assist you in this process. I would grant you access to Fleek, but unfortunately, due to Fleek migrating from [Fleek.co](http://fleek.co/) to Fleek.xyz, they are not allowing creation of new users on [Fleek.co](http://fleek.co/), which our account is a [Fleek.co](http://fleek.co/) account.  Instead, I will send you screenshots of the site setting pages, env variables and anything else you should need.

I confirmed the screenshots don't have anything sensitive.  I'm uploading them here for visibility.

![lotus filecoin io-deployments](https://github.com/user-attachments/assets/6c9cb54f-b18c-459f-a577-eb04b1fbe2de)
![lotus filecoin io-general](https://github.com/user-attachments/assets/8fe66706-e50b-4725-abe1-ece40ce19825)
![lotus filecoin io-settings-build-and-deploy-1](https://github.com/user-attachments/assets/3e6d659d-e592-4077-865c-b1a0c1eca025)
![lotus filecoin io-settings-build-and-deploy-2](https://github.com/user-attachments/assets/69662a0a-5a36-47df-8b97-666dc7abf62a)
![lotus filecoin io-settings-build-and-deploy-3](https://github.com/user-attachments/assets/cfb1aa39-4a3d-444b-b7fb-d2414df43fee)
![lotus filecoin io-settings-domains-1](https://github.com/user-attachments/assets/241324d5-3731-4103-aa76-3620e321ae53)
![lotus filecoin io-settings-domains-2](https://github.com/user-attachments/assets/7b6173ec-6851-41c3-b42a-07b56d4ad146)
![lotus filecoin io-settings-general-1](https://github.com/user-attachments/assets/0eff6095-dd12-4903-91fe-bcbc173f4188)
![lotus filecoin io-settings-general-2](https://github.com/user-attachments/assets/3da90ca3-a35f-49ea-ab24-e807dfc9349b)

**Comment by rjan90** [comment]
> Login email: [infa@fleek.xyz](mailto:infa@fleek.xyz)
> Username: filoz
> There isn't a password since uses email verification for login.

Just confirming that this is a typo? Login email should be infra@filoz.org right?

**Comment by BigLep** [comment]
> Just confirming that this is a typo? Login email should be [infra@filoz.org](mailto:infra@filoz.org) right?

Doh - yes - typo.  Fixed above.  Thanks.

**Comment by BigLep** [comment]
2024-08-16 update:
1. I have updated the tasklist in the issue description with what I think is remaining.
2. Publishing to https://lotus-docs.on-fleek.app/ is working
3. I sent a support request to fleek.xyz to get help with lotus.filecoin.io subdomain:

```
Hello,

I am attempting to move lotus.filecoin.io out from a shared Protocol Labs Inc fleek.co account to a new fleek.xyz account I created for infra@filoz.org since we (FilOz) are the direct owners of this site.

Publishing to https://lotus-docs.on-fleek.app/ is working fine, but I am unable to setup the lotus.filecoin.io subdomain.  At https://app.fleek.xyz/projects/clzvt6im10003uvgp4imdo563/sites/clzwyimfj0000pjik3l3z33of/settings/domains/ I just see the message "Creation Failed" but I don't know why.  I wasn't given any opportunity to configure DNS, CNAMEs, etc.

Any help or pointers here are welcome.

Thanks,
Steve Loeppky

(Note: we're tracking this migration in https://github.com/filecoin-project/lotus-docs/issues/742)
```

4. I started documenting public publishing in https://github.com/filecoin-project/lotus-docs/pull/756
5. I made a feedback request on giving easier to access one-click preview links like fleek.co had:

```
Hello,

I'm moving a site from fleek.co to fleek.xyz per https://github.com/filecoin-project/lotus-docs/issues/742 .  In comparing the two integrations for a sample PR (https://github.com/filecoin-project/lotus-docs/pull/756 ), I see that fleek.xyz doesn't have the same nice inline one-click link to go see the preview site like fleek.co has.  I instead need to go hunt for it in the GitHub Action logs: https://github.com/filecoin-project/lotus-docs/pull/756/checks?check_run_id=28871003552 .  Is there something I need to do to enable this?

Thanks,
Steve
```

**Comment by BigLep** [comment]
@rjan90 and @TippyFlitsUK :on handling lotus docs and the shutdown of shared accounts from PL Inc like this issue, do you know which of these integrations (screenshot) still apply?
https://github.com/filecoin-project/lotus-docs/settings/installations
<img width="783" alt="image" src="https://github.com/user-attachments/assets/5446a10a-bf43-4821-b2fd-ef690f063975">

- [fleek.co](http://fleek.co/) will go away as part of https://github.com/filecoin-project/lotus-docs/issues/742
- [gitpod.io](http://gitpod.io/)?  I don't see anything in infra vault to check on this and I can't find anything in the repo: https://github.com/search?q=repo%3Afilecoin-project%2Flotus-docs%20gitpod&type=code
- Netlify?  I don't see anything in infra vault to check on this and it's not clear to me from looking at the files in the repo: https://github.com/search?q=repo%3Afilecoin-project%2Flotus-docs+netlify&type=code
- Render? I don't see anything in infra vault to check on this and I can't find anything in the repo: https://github.com/search?q=repo%3Afilecoin-project%2Flotus-docs+render&type=code

Can we just simplify to publishing/hosting with fleek.xyz only and remove the other integrations or would you like to see something else?

I want to document how we do public publishing.  I started here https://github.com/filecoin-project/lotus-docs/pull/756 and will add more as learn more.

**Comment by rjan90** [comment]
> Can we just simplify to publishing/hosting with fleek.xyz only and remove the other integrations or would you like to see something else?

Yes, I think we can remove the other integrations - I do not see anything in there that we are currently using.

**Comment by BigLep** [comment]
2024-08-22 status update: there was a problem with Fleek's ticketing system according to Fleek admins on discord: https://discord.com/channels/965698989464887386/994678775851794493/1276157729450496023 .  I resubmitted the support request and will engage on once they reply.

**Comment by BigLep** [comment]
2024-08-23 status update: we've heard back from Fleek on what we need to do to get unblocked.  We effectively need to delete the domain from the PL Inc fleek.co account.

I have time scheduled on Mon Aug 26, 2024 2pm – 2:30pm (PDT) with [@Daniel Bisgrove (SEAD)](https://filecoinproject.slack.com/team/U07517VLVL5) so we can screenshare and handle the transition since he has access to PL Inc fleek.co account and filecoin.io DNS and I have access to infra@filoz.org fleek.xyz account.  There will be a small amount of downtime during this transition.

I will look today at the DNS records to see if we can adjust timeouts to minimize the downtime.  I'll report back here once I have done so.

**Comment by BigLep** [comment]
@rjan90 : Per DNS dump below, it looks like lotus.filecoin.io is currently be served by Netlify for traditional web2/https traffic.  Do you have access to that account?  I'll also ask SEAD.  With the move to Fleek, I'll get this shut down.  

<details><summary>DNS dump from https://dnschecker.org/all-dns-records-of-domain.php?query=lotus.filecoin.io&rtype=ALL&dns=google</summary>

# A Records 

| Name | TTL | Data | 
|------|-----|------|
| lotus.filecoin.io | 20 | 35.169.59.174 | 
| lotus.filecoin.io | 20 | 44.217.161.11 | 

# AAAA Records 

| Name | TTL | Data | 
|------|-----|------|
| lotus.filecoin.io | 20 | 2600:1f18:16e:df01::64 | 
| lotus.filecoin.io | 20 | 2600:1f18:2489:8202::c8 | 

# CNAME Records 

| Name | TTL | Data | 
|------|-----|------|
| lotus.filecoin.io | 600 | lotus-docs-mirror.netlify.app. | 

# MX Records 

 No records present.

# NS Records 

 No records present.

# PTR Records 

 No records present.

# SRV Records 

 No records present.

# SOA Records 

 No records present.

# TXT Records 

 No records present.

# CAA Records 

 No records present.

# DS Records 

 No records present.

# DNSKEY Records 

 No records present.

</details>

**Comment by BigLep** [comment]
2024-08-26 update: lotus.filecoin.io is configured with the FilOz fleek.xyz account.  I have confirmed DNS records were updated using https://dnschecker.org/all-dns-records-of-domain.php?query=lotus.filecoin.io&rtype=ALL&dns=google and I have had no issues loading the site.

Assuming no issues reported in the next 12-24 hours:
1. SEAD will remove lotus.filecion.io from PL Inc fleek.co account
2. I will remove the other [legacy app integrations](https://github.com/filecoin-project/lotus-docs/issues/742#issuecomment-2293910268)

The checklist at the top of the issue is accurate.  I'll need @rjan90 support to finish a couple of them.

**Comment by BigLep** [comment]
I'm resolving the issue as all checklist items have been completed, including removing unused integrations.  These are what remain at https://github.com/filecoin-project/lotus-docs/settings/installations

<img width="790" alt="image" src="https://github.com/user-attachments/assets/974f6458-260b-4b7e-95b6-333dc5ddc606">
