### ISSUE TITLE
Move Lotus Documentation into Lotus Repo

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#765]
## Done Criteria
- Decision made on whether to move Lotus documentation back into the Lotus repo
- Plan created for migration if decision is to move documentation
- Implementation of the migration plan if approved

## Why Important
The current separation of the Lotus documentation into a different repository adds a barrier to updating the documentation alongside code updates. Moving the documentation back into the Lotus repo would make it easier for contributors to update the documentation along with code changes.

## User/Customer
Lotus maintainers and contributors

## Notes
There are concerns about the migration costs and bandwidth, at least in the 2024H2. We are writing this ticket up only to bring it up when planning for Q1/Q2 in 2025.

```[tasklist]
## Tasks
- [ ] Discuss the proposal with the team
- [ ] Evaluate the migration costs and bandwidth
- [ ] Create a plan for the migration if approved
- [ ] Implement the migration plan if approved
```
